### PR TITLE
Update Catch to version 2.13.1

### PR DESCRIPTION
**Pull request by sven-herrmann**

### CODE REVIEW

**Comment by shr-project** [comment]
Pity this still wasn't reviewed and merged, for glibc-2.34 compatibility this wrapper would need to import
https://github.com/catchorg/Catch2/commit/c0d0a50bdb2ae2f749443c0386c2b25379bdbf76 with 2.13.5 Catch2 (see https://github.com/catchorg/Catch2/issues/2178) but seeing this PR abandoned for over a year, it's probably not worth submitting another, right?

**Comment by xqms** [comment]
I'm sorry, somehow this was never properly reviewed :disappointed:
In such cases, it's ok to remind maintainers that the PR needs attention!

@shr-project I'm open to reviewing & merging a PR that updates the Catch version :+1:

**Comment by shr-project** [comment]
@xqms ok thanks, see https://github.com/AIS-Bonn/catch_ros/pull/15

**Comment by xqms** [comment]
Closed in favor of #15.

**Pull request closed without merging**
