### PR TITLE
updated catch to 2.4.2

### PR DESCRIPTION
**Pull request by mez**
Here is just the catch update!

cheers

### CODE REVIEW

**Comment by xqms** [comment]
@ros-pull-request-builder retest this please

**Comment by xqms** [comment]
Okay, I removed your `.gitignore` change from the commit - you can use `.git/info/exclude` for your local purposes.

I'm ready to merge this, but I noticed that your e-mail is not set up correctly in the commit metadata (shows `mez@xps`). Would you like to fix that?

The commit e-mails are used to identify and honor contributors in the changelog and official ROS release notifications.

**Comment by mez** [comment]
OK, made the changes!

**Comment by xqms** [comment]
squashed & merged, thanks!

**Pull request merged**
